### ISSUE TITLE
Fill/Stroke color

### ISSUE THREAD

**Issue by costavale** [LauLauThom/RoiGroupTable#2]
Do you think it will be possible to add also the choice for the fill and stroke colours?
Thank you!

**Comment by LauLauThom** [comment]
The stroke colour is predefined for a given Roi group, following the values of the Glasbey Look Up Table (except for group 0/no group, which stays to the original yellow colour). 
It a simple solution we adopted for ImageJ to have rois of the same group with identical colours.
 
So no currently there is no way to set a custom colour for a given group, sorry...

Alternatively, we could add the option in ImageJ, to use another Look Up Table instead of the default Glasbey LUT.
That could be interesting when the Roi Group is used to reflect a quantitative value (e.g the mean gray value within the ROI), then the stroke colour could follow a quantitative/continuous LUT (like the red/green, or Fire LUT). 

For the fill colour, I think we did not implement anything. 
Having the roi-group defining both the fill color and the stroke color help ? (ie stoke color = fill color for a given group). 
For what use case do you need it ?

**Comment by costavale** [comment]
Thank you for the clarification! 
And for the very useful plugin.
In our case, we are using the different groups to identify areas of benthic species and to measure them:

![WhatsApp Image 2021-12-06 at 3 55 41 PM](https://user-images.githubusercontent.com/12810216/144878841-f3d0da81-e91b-4dc8-89cb-e914899c4d89.jpeg)

The fill/stroke colour will be useful to visualize the species and to create an image ready for publication.

**Comment by LauLauThom** [comment]
As a workaround, you could try to pick a group number that has a colour that you like. 
To do so, Image > Color > Display LUTs in ImageJ menu, then crop the region corresponding to the glasbey LUT (or maybe the inverted glasbey I am not sure which one we used). To have something like shown here https://imagej.net/plugins/glasbey
This way using the mouse to point at the color of interest, the X-position of the mouse (to read from the ImageJ toolbar) will give you the group to use. Dont hesitate to zoom in.

I would advise to outline only, not fill, unless you really need a mask image. With filling one cannot see the image below 😅
You can adjust the default width of the outline to make it bolder (double click the rectangle ROI tool).
